#!/bin/bash
set -e

# NJS Pipeline Entrypoint
# Validates environment, creates .env, and runs pipeline

echo "==================================================================="
echo "NJS Pipeline Container Starting"
echo "==================================================================="
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "Mode: ${PIPELINE_MODE:-run-once}"
echo "==================================================================="

# Function to log messages
log() {
    echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $1"
}

# Validate required environment variables
log "Validating environment variables..."
required_vars=(
    "WAZUH_API_URL"
    "WAZUH_API_USERNAME"
    "WAZUH_API_PASSWORD"
    "NEO4J_URI"
    "NEO4J_USERNAME"
    "NEO4J_PASSWORD"
    "BANK_ID"
    "SHARED_DATA_PATH"
)

missing_vars=()
for var in "${required_vars[@]}"; do
    if [ -z "${!var}" ]; then
        missing_vars+=("$var")
    fi
done

if [ ${#missing_vars[@]} -gt 0 ]; then
    log "ERROR: Missing required environment variables:"
    for var in "${missing_vars[@]}"; do
        log "  - $var"
    done
    exit 1
fi

log "✅ All required environment variables present"

# Create .env file from environment variables
log "Creating .env file..."
cat > /app/.env <<EOF
# Auto-generated by Docker entrypoint
# Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Wazuh Configuration
WAZUH_API_URL=${WAZUH_API_URL}
WAZUH_API_USERNAME=${WAZUH_API_USERNAME}
WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}

# Neo4j Configuration
NEO4J_URI=${NEO4J_URI}
NEO4J_USERNAME=${NEO4J_USERNAME}
NEO4J_PASSWORD=${NEO4J_PASSWORD}
NEO4J_NODE_DATABASE=${NEO4J_NODE_DATABASE:-node_kg}
NEO4J_CORE_DATABASE=${NEO4J_CORE_DATABASE:-core}

# Bank Configuration
BANK_ID=${BANK_ID}

# Shared Data Path
SHARED_DATA_PATH=${SHARED_DATA_PATH}

# Pipeline Configuration
PIPELINE_MODE=${PIPELINE_MODE:-run-once}
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF

log "✅ .env file created"

# Create shared data directories if they don't exist
log "Setting up shared data directories..."
mkdir -p ${SHARED_DATA_PATH}/{data/{collected,extracted,aggregated,aggregated_core,pii_scan_results},logs,pipeline,config}

log "✅ Shared data directories ready"

# Wait for Neo4j to be ready
log "Waiting for Neo4j to be ready..."
max_attempts=30
attempt=0

until cypher-shell -a ${NEO4J_URI} -u ${NEO4J_USERNAME} -p ${NEO4J_PASSWORD} "RETURN 1" > /dev/null 2>&1; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        log "ERROR: Neo4j failed to start after ${max_attempts} attempts"
        exit 1
    fi
    log "Neo4j is unavailable - attempt ${attempt}/${max_attempts}"
    sleep 2
done

log "✅ Neo4j is ready!"

# Execute command based on argument
case "$1" in
    run-pipeline)
        log "Starting pipeline in run-once mode..."
        poetry run python /app/scripts/orchestrator.py
        ;;
    
    run-scheduled)
        log "Starting pipeline in scheduled mode..."
        log "Schedule: ${PIPELINE_SCHEDULE:-0 2 * * *}"
        # TODO: Implement cron-based scheduling
        # For now, run once
        poetry run python /app/scripts/orchestrator.py
        ;;
    
    run-step)
        if [ -z "$2" ]; then
            log "ERROR: Step name required. Usage: run-step <step_name>"
            exit 1
        fi
        log "Running single step: $2"
        poetry run python /app/scripts/orchestrator.py --step "$2"
        ;;
    
    shell)
        log "Starting interactive shell..."
        exec /bin/bash
        ;;
    
    *)
        log "Executing custom command: $@"
        exec "$@"
        ;;
esac

exit_code=$?
log "==================================================================="
log "Pipeline completed with exit code: ${exit_code}"
log "==================================================================="
exit ${exit_code}
