# Configuration settings
EENADU_BASE_URL = "https://www.eenadu.net"

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5,te;q=0.3',
    'Accept-Encoding': 'gzip, deflate',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1'
}

# Telugu News Sources Configuration - Comprehensive Reliable Sources
NEWS_SOURCES = [
    # Major Telugu Newspapers
    {"value": "eenadu", "label": "Eenadu", "url": "https://www.eenadu.net", "type": "newspaper"},
    {"value": "sakshi", "label": "Sakshi", "url": "https://www.sakshi.com", "type": "newspaper"},
    {"value": "andhrajyothy", "label": "Andhra Jyothy", "url": "https://www.andhrajyothy.com", "type": "newspaper"},
    {"value": "vaartha", "label": "Vaartha", "url": "https://www.vaartha.com", "type": "newspaper"},
    {"value": "suryaa", "label": "Suryaa", "url": "https://www.suryaa.com", "type": "newspaper"},
    {"value": "prajasakti", "label": "Praja Sakti", "url": "https://www.prajasakti.com", "type": "newspaper"},
    {"value": "namasthetelangana", "label": "Namasthe Telangana", "url": "https://www.namasthetelangana.com", "type": "newspaper"},
    {"value": "surya", "label": "Surya", "url": "https://www.surya.tv", "type": "newspaper"},
    
    # TV News Channels
    {"value": "tv9telugu", "label": "TV9 Telugu", "url": "https://www.tv9telugu.com", "type": "tv"},
    {"value": "ntv", "label": "NTV Telugu", "url": "https://www.ntvtelugu.com", "type": "tv"},
    {"value": "hmtv", "label": "HMTV", "url": "https://www.hmtv.in", "type": "tv"},
    {"value": "10tv", "label": "10TV", "url": "https://www.10tv.in", "type": "tv"},
    {"value": "abn", "label": "ABN Telugu", "url": "https://www.abntelugu.com", "type": "tv"},
    {"value": "cvr", "label": "CVR News", "url": "https://www.cvrnews.com", "type": "tv"},
    {"value": "mahaa", "label": "Mahaa News", "url": "https://www.mahaanews.com", "type": "tv"},
    {"value": "v6news", "label": "V6 News", "url": "https://www.v6velugu.com", "type": "tv"},
    {"value": "etv", "label": "ETV Telugu", "url": "https://www.etv.co.in", "type": "tv"},
    {"value": "gemini", "label": "Gemini TV", "url": "https://www.geminitv.com", "type": "tv"},
    {"value": "tv5", "label": "TV5 News", "url": "https://www.tv5news.in", "type": "tv"},
    {"value": "99tv", "label": "99TV", "url": "https://www.99tv.in", "type": "tv"},
    {"value": "studio_n", "label": "Studio N", "url": "https://www.studion.news", "type": "tv"},
    
    # Digital News Platforms
    {"value": "greatandhra", "label": "Great Andhra", "url": "https://www.greatandhra.com", "type": "digital"},
    {"value": "123telugu", "label": "123Telugu", "url": "https://www.123telugu.com", "type": "digital"},
    {"value": "telugu360", "label": "Telugu360", "url": "https://www.telugu360.com", "type": "digital"},
    {"value": "thenewsminute", "label": "The News Minute Telugu", "url": "https://telugu.thenewsminute.com", "type": "digital"},
    {"value": "webdunia", "label": "Webdunia Telugu", "url": "https://telugu.webdunia.com", "type": "digital"},
    {"value": "oneindia", "label": "OneIndia Telugu", "url": "https://telugu.oneindia.com", "type": "digital"},
    {"value": "indianexpress", "label": "Indian Express Telugu", "url": "https://telugu.indianexpress.com", "type": "digital"},
    {"value": "deccanchronicle", "label": "Deccan Chronicle Telugu", "url": "https://www.deccanchronicle.com/telugu", "type": "digital"},
    {"value": "thehindu", "label": "The Hindu Telugu", "url": "https://www.thehindu.com/telugu", "type": "digital"},
    {"value": "timesnow", "label": "Times Now Telugu", "url": "https://www.timesnownews.com/telugu", "type": "digital"},
    {"value": "news18", "label": "News18 Telugu", "url": "https://telugu.news18.com", "type": "digital"},
    {"value": "indiatoday", "label": "India Today Telugu", "url": "https://www.indiatoday.in/telugu", "type": "digital"},
    {"value": "ndtv", "label": "NDTV Telugu", "url": "https://telugu.ndtv.com", "type": "digital"},
    {"value": "aajtak", "label": "Aaj Tak Telugu", "url": "https://www.aajtak.in/telugu", "type": "digital"},
    
    # Regional & Specialized
    {"value": "gulte", "label": "Gulte", "url": "https://www.gulte.com", "type": "entertainment"},
    {"value": "cinejosh", "label": "CineJosh", "url": "https://www.cinejosh.com", "type": "entertainment"},
    {"value": "tollywood", "label": "Tollywood.net", "url": "https://www.tollywood.net", "type": "entertainment"},
    {"value": "idlebrain", "label": "Idlebrain", "url": "https://www.idlebrain.com", "type": "entertainment"},
    {"value": "ragalahari", "label": "Ragalahari", "url": "https://www.ragalahari.com", "type": "entertainment"},
    {"value": "telugucinema", "label": "Telugu Cinema", "url": "https://www.telugucinema.com", "type": "entertainment"},
    {"value": "filmibeat", "label": "Filmibeat Telugu", "url": "https://telugu.filmibeat.com", "type": "entertainment"},
    {"value": "bollywoodlife", "label": "Bollywood Life Telugu", "url": "https://telugu.bollywoodlife.com", "type": "entertainment"},
    
    # Sports Specialized
    {"value": "sportskeeda", "label": "Sportskeeda Telugu", "url": "https://telugu.sportskeeda.com", "type": "sports"},
    {"value": "cricbuzz", "label": "Cricbuzz Telugu", "url": "https://telugu.cricbuzz.com", "type": "sports"},
    {"value": "espn", "label": "ESPN Telugu", "url": "https://telugu.espn.in", "type": "sports"},
    
    # Business & Finance
    {"value": "businessline", "label": "Business Line Telugu", "url": "https://telugu.thehindubusinessline.com", "type": "business"},
    {"value": "economictimes", "label": "Economic Times Telugu", "url": "https://telugu.economictimes.com", "type": "business"},
    {"value": "moneycontrol", "label": "Moneycontrol Telugu", "url": "https://telugu.moneycontrol.com", "type": "business"},
    
    # Technology
    {"value": "gadgets360", "label": "Gadgets 360 Telugu", "url": "https://telugu.gadgets360.com", "type": "technology"},
    {"value": "techcrunch", "label": "TechCrunch Telugu", "url": "https://telugu.techcrunch.com", "type": "technology"}
]

CATEGORY_URLS = {
    "politics": "/andhra-pradesh",
    "sports": "/sports", 
    "business": "/business",
    "entertainment": "/cinema",
    "technology": "/technology",
    "health": "/health",
    "education": "/education",
    "crime": "/crime",
    "international": "/international",
    "national": "/national",
    "telangana": "/telangana",
    "andhra-pradesh": "/andhra-pradesh",
    "hyderabad": "/hyderabad",
    "vijayawada": "/vijayawada",
    "visakhapatnam": "/visakhapatnam",
    "agriculture": "/agriculture",
    "lifestyle": "/lifestyle",
    "opinion": "/opinion",
    "editorial": "/editorial",
    "weather": "/weather",
    "astrology": "/astrology"
}

CATEGORIES = [
    # General Categories
    {"value": "", "label": "🏠 Home Page", "group": "general"},
    {"value": "breaking", "label": "🚨 Breaking News", "group": "general"},
    {"value": "trending", "label": "📈 Trending", "group": "general"},
    {"value": "latest", "label": "🆕 Latest News", "group": "general"},
    {"value": "top-stories", "label": "⭐ Top Stories", "group": "general"},
    
    # Politics & Governance
    {"value": "politics", "label": "🏛️ Politics", "group": "politics"},
    {"value": "national", "label": "🇮🇳 National", "group": "politics"},
    {"value": "international", "label": "🌍 International", "group": "politics"},
    {"value": "elections", "label": "🗳️ Elections", "group": "politics"},
    {"value": "government", "label": "🏢 Government", "group": "politics"},
    {"value": "parliament", "label": "🏛️ Parliament", "group": "politics"},
    {"value": "assembly", "label": "🏛️ Assembly", "group": "politics"},
    {"value": "municipal", "label": "🏢 Municipal", "group": "politics"},
    {"value": "panchayat", "label": "🏘️ Panchayat", "group": "politics"},
    {"value": "bjp", "label": "🟠 BJP", "group": "politics"},
    {"value": "congress", "label": "🔵 Congress", "group": "politics"},
    {"value": "trs", "label": "🟣 TRS/BRS", "group": "politics"},
    {"value": "tdp", "label": "🟡 TDP", "group": "politics"},
    {"value": "ysrcp", "label": "🔴 YSRCP", "group": "politics"},
    {"value": "janasena", "label": "🟢 Jana Sena", "group": "politics"},
    
    # Regional Coverage
    {"value": "telangana", "label": "🏛️ Telangana", "group": "regional"},
    {"value": "andhra-pradesh", "label": "🏛️ Andhra Pradesh", "group": "regional"},
    {"value": "hyderabad", "label": "🏙️ Hyderabad", "group": "regional"},
    {"value": "secunderabad", "label": "🏙️ Secunderabad", "group": "regional"},
    {"value": "vijayawada", "label": "🏙️ Vijayawada", "group": "regional"},
    {"value": "visakhapatnam", "label": "🏙️ Visakhapatnam", "group": "regional"},
    {"value": "guntur", "label": "🏙️ Guntur", "group": "regional"},
    {"value": "tirupati", "label": "🏙️ Tirupati", "group": "regional"},
    {"value": "kakinada", "label": "🏙️ Kakinada", "group": "regional"},
    {"value": "nellore", "label": "🏙️ Nellore", "group": "regional"},
    {"value": "kurnool", "label": "🏙️ Kurnool", "group": "regional"},
    {"value": "warangal", "label": "🏙️ Warangal", "group": "regional"},
    {"value": "nizamabad", "label": "🏙️ Nizamabad", "group": "regional"},
    {"value": "karimnagar", "label": "🏙️ Karimnagar", "group": "regional"},
    {"value": "khammam", "label": "🏙️ Khammam", "group": "regional"},
    {"value": "mahbubnagar", "label": "🏙️ Mahbubnagar", "group": "regional"},
    {"value": "medak", "label": "🏙️ Medak", "group": "regional"},
    {"value": "rangareddy", "label": "🏙️ Rangareddy", "group": "regional"},
    {"value": "adilabad", "label": "🏙️ Adilabad", "group": "regional"},
    {"value": "anantapur", "label": "🏙️ Anantapur", "group": "regional"},
    {"value": "chittoor", "label": "🏙️ Chittoor", "group": "regional"},
    {"value": "kadapa", "label": "🏙️ Kadapa", "group": "regional"},
    {"value": "prakasam", "label": "🏙️ Prakasam", "group": "regional"},
    {"value": "srikakulam", "label": "🏙️ Srikakulam", "group": "regional"},
    {"value": "vizianagaram", "label": "🏙️ Vizianagaram", "group": "regional"},
    {"value": "west-godavari", "label": "🏙️ West Godavari", "group": "regional"},
    {"value": "east-godavari", "label": "🏙️ East Godavari", "group": "regional"},
    
    # Sports
    {"value": "sports", "label": "⚽ Sports", "group": "sports"},
    {"value": "cricket", "label": "🏏 Cricket", "group": "sports"},
    {"value": "ipl", "label": "🏏 IPL", "group": "sports"},
    {"value": "football", "label": "⚽ Football", "group": "sports"},
    {"value": "tennis", "label": "🎾 Tennis", "group": "sports"},
    {"value": "badminton", "label": "🏸 Badminton", "group": "sports"},
    {"value": "kabaddi", "label": "🤼 Kabaddi", "group": "sports"},
    {"value": "hockey", "label": "🏑 Hockey", "group": "sports"},
    {"value": "wrestling", "label": "🤼 Wrestling", "group": "sports"},
    {"value": "boxing", "label": "🥊 Boxing", "group": "sports"},
    {"value": "athletics", "label": "🏃 Athletics", "group": "sports"},
    {"value": "swimming", "label": "🏊 Swimming", "group": "sports"},
    {"value": "olympics", "label": "🏅 Olympics", "group": "sports"},
    {"value": "commonwealth", "label": "🏅 Commonwealth Games", "group": "sports"},
    {"value": "asian-games", "label": "🏅 Asian Games", "group": "sports"},
    
    # Business & Economy
    {"value": "business", "label": "💼 Business", "group": "business"},
    {"value": "economy", "label": "📊 Economy", "group": "business"},
    {"value": "finance", "label": "💰 Finance", "group": "business"},
    {"value": "stock-market", "label": "📈 Stock Market", "group": "business"},
    {"value": "banking", "label": "🏦 Banking", "group": "business"},
    {"value": "insurance", "label": "🛡️ Insurance", "group": "business"},
    {"value": "mutual-funds", "label": "📊 Mutual Funds", "group": "business"},
    {"value": "cryptocurrency", "label": "₿ Cryptocurrency", "group": "business"},
    {"value": "real-estate", "label": "🏠 Real Estate", "group": "business"},
    {"value": "startups", "label": "🚀 Startups", "group": "business"},
    {"value": "industry", "label": "🏭 Industry", "group": "business"},
    {"value": "manufacturing", "label": "⚙️ Manufacturing", "group": "business"},
    {"value": "retail", "label": "🛒 Retail", "group": "business"},
    {"value": "e-commerce", "label": "🛍️ E-commerce", "group": "business"},
    {"value": "taxation", "label": "💸 Taxation", "group": "business"},
    {"value": "budget", "label": "📋 Budget", "group": "business"},
    {"value": "gdp", "label": "📊 GDP", "group": "business"},
    {"value": "inflation", "label": "📈 Inflation", "group": "business"},
    
    # Entertainment
    {"value": "entertainment", "label": "🎬 Entertainment", "group": "entertainment"},
    {"value": "cinema", "label": "🎭 Cinema", "group": "entertainment"},
    {"value": "tollywood", "label": "🎬 Tollywood", "group": "entertainment"},
    {"value": "bollywood", "label": "🎬 Bollywood", "group": "entertainment"},
    {"value": "hollywood", "label": "🎬 Hollywood", "group": "entertainment"},
    {"value": "kollywood", "label": "🎬 Kollywood", "group": "entertainment"},
    {"value": "sandalwood", "label": "🎬 Sandalwood", "group": "entertainment"},
    {"value": "mollywood", "label": "🎬 Mollywood", "group": "entertainment"},
    {"value": "music", "label": "🎵 Music", "group": "entertainment"},
    {"value": "classical-music", "label": "🎼 Classical Music", "group": "entertainment"},
    {"value": "folk-music", "label": "🎶 Folk Music", "group": "entertainment"},
    {"value": "celebrity", "label": "⭐ Celebrity", "group": "entertainment"},
    {"value": "gossip", "label": "💬 Gossip", "group": "entertainment"},
    {"value": "awards", "label": "🏆 Awards", "group": "entertainment"},
    {"value": "box-office", "label": "💰 Box Office", "group": "entertainment"},
    {"value": "ott", "label": "📺 OTT", "group": "entertainment"},
    {"value": "netflix", "label": "📺 Netflix", "group": "entertainment"},
    {"value": "amazon-prime", "label": "📺 Amazon Prime", "group": "entertainment"},
    {"value": "disney-hotstar", "label": "📺 Disney+ Hotstar", "group": "entertainment"},
    {"value": "zee5", "label": "📺 Zee5", "group": "entertainment"},
    {"value": "sony-liv", "label": "📺 Sony LIV", "group": "entertainment"},
    {"value": "television", "label": "📺 Television", "group": "entertainment"},
    {"value": "reality-shows", "label": "📺 Reality Shows", "group": "entertainment"},
    {"value": "web-series", "label": "💻 Web Series", "group": "entertainment"},
    
    # Technology
    {"value": "technology", "label": "💻 Technology", "group": "technology"},
    {"value": "gadgets", "label": "📱 Gadgets", "group": "technology"},
    {"value": "mobile", "label": "📱 Mobile", "group": "technology"},
    {"value": "smartphones", "label": "📱 Smartphones", "group": "technology"},
    {"value": "laptops", "label": "💻 Laptops", "group": "technology"},
    {"value": "tablets", "label": "📱 Tablets", "group": "technology"},
    {"value": "internet", "label": "🌐 Internet", "group": "technology"},
    {"value": "social-media", "label": "📱 Social Media", "group": "technology"},
    {"value": "facebook", "label": "📘 Facebook", "group": "technology"},
    {"value": "instagram", "label": "📷 Instagram", "group": "technology"},
    {"value": "twitter", "label": "🐦 Twitter", "group": "technology"},
    {"value": "whatsapp", "label": "💬 WhatsApp", "group": "technology"},
    {"value": "youtube", "label": "📺 YouTube", "group": "technology"},
    {"value": "google", "label": "🔍 Google", "group": "technology"},
    {"value": "microsoft", "label": "🪟 Microsoft", "group": "technology"},
    {"value": "apple", "label": "🍎 Apple", "group": "technology"},
    {"value": "samsung", "label": "📱 Samsung", "group": "technology"},
    {"value": "software", "label": "💿 Software", "group": "technology"},
    {"value": "apps", "label": "📱 Apps", "group": "technology"},
    {"value": "ai", "label": "🤖 Artificial Intelligence", "group": "technology"},
    {"value": "machine-learning", "label": "🧠 Machine Learning", "group": "technology"},
    {"value": "blockchain", "label": "⛓️ Blockchain", "group": "technology"},
    {"value": "cybersecurity", "label": "🔒 Cybersecurity", "group": "technology"},
    {"value": "data-privacy", "label": "🔐 Data Privacy", "group": "technology"},
    {"value": "5g", "label": "📶 5G", "group": "technology"},
    {"value": "iot", "label": "🌐 IoT", "group": "technology"},
    {"value": "cloud-computing", "label": "☁️ Cloud Computing", "group": "technology"},
    {"value": "gaming", "label": "🎮 Gaming", "group": "technology"},
    {"value": "esports", "label": "🎮 Esports", "group": "technology"},
    
    # Health & Medicine
    {"value": "health", "label": "🏥 Health", "group": "health"},
    {"value": "medicine", "label": "💊 Medicine", "group": "health"},
    {"value": "hospitals", "label": "🏥 Hospitals", "group": "health"},
    {"value": "doctors", "label": "👨‍⚕️ Doctors", "group": "health"},
    {"value": "fitness", "label": "💪 Fitness", "group": "health"},
    {"value": "yoga", "label": "🧘 Yoga", "group": "health"},
    {"value": "nutrition", "label": "🥗 Nutrition", "group": "health"},
    {"value": "diet", "label": "🍎 Diet", "group": "health"},
    {"value": "mental-health", "label": "🧠 Mental Health", "group": "health"},
    {"value": "wellness", "label": "🌿 Wellness", "group": "health"},
    {"value": "covid", "label": "🦠 COVID-19", "group": "health"},
    {"value": "vaccination", "label": "💉 Vaccination", "group": "health"},
    {"value": "pandemic", "label": "🌍 Pandemic", "group": "health"},
    {"value": "ayurveda", "label": "🌿 Ayurveda", "group": "health"},
    {"value": "homeopathy", "label": "💊 Homeopathy", "group": "health"},
    {"value": "medical-research", "label": "🔬 Medical Research", "group": "health"},
    {"value": "pharmaceuticals", "label": "💊 Pharmaceuticals", "group": "health"},
    {"value": "healthcare-policy", "label": "📋 Healthcare Policy", "group": "health"},
    
    # Education
    {"value": "education", "label": "🎓 Education", "group": "education"},
    {"value": "schools", "label": "🏫 Schools", "group": "education"},
    {"value": "colleges", "label": "🏛️ Colleges", "group": "education"},
    {"value": "universities", "label": "🏛️ Universities", "group": "education"},
    {"value": "exams", "label": "📝 Exams", "group": "education"},
    {"value": "results", "label": "📊 Results", "group": "education"},
    {"value": "admissions", "label": "📋 Admissions", "group": "education"},
    {"value": "scholarships", "label": "💰 Scholarships", "group": "education"},
    {"value": "competitive-exams", "label": "📚 Competitive Exams", "group": "education"},
    {"value": "jee", "label": "📚 JEE", "group": "education"},
    {"value": "neet", "label": "📚 NEET", "group": "education"},
    {"value": "upsc", "label": "📚 UPSC", "group": "education"},
    {"value": "ssc", "label": "📚 SSC", "group": "education"},
    {"value": "banking-exams", "label": "📚 Banking Exams", "group": "education"},
    {"value": "railway-exams", "label": "📚 Railway Exams", "group": "education"},
    {"value": "police-exams", "label": "📚 Police Exams", "group": "education"},
    {"value": "teaching-jobs", "label": "👨‍🏫 Teaching Jobs", "group": "education"},
    {"value": "online-education", "label": "💻 Online Education", "group": "education"},
    {"value": "skill-development", "label": "🛠️ Skill Development", "group": "education"},
    {"value": "vocational-training", "label": "🔧 Vocational Training", "group": "education"},
    
    # Crime & Law
    {"value": "crime", "label": "🚔 Crime", "group": "crime"},
    {"value": "police", "label": "👮 Police", "group": "crime"},
    {"value": "court", "label": "⚖️ Court", "group": "crime"},
    {"value": "legal", "label": "📜 Legal", "group": "crime"},
    {"value": "supreme-court", "label": "⚖️ Supreme Court", "group": "crime"},
    {"value": "high-court", "label": "⚖️ High Court", "group": "crime"},
    {"value": "cybercrime", "label": "💻 Cybercrime", "group": "crime"},
    {"value": "fraud", "label": "💰 Fraud", "group": "crime"},
    {"value": "corruption", "label": "💰 Corruption", "group": "crime"},
    {"value": "investigation", "label": "🔍 Investigation", "group": "crime"},
    {"value": "arrest", "label": "🚔 Arrest", "group": "crime"},
    {"value": "bail", "label": "⚖️ Bail", "group": "crime"},
    {"value": "verdict", "label": "⚖️ Verdict", "group": "crime"},
    {"value": "sentence", "label": "⚖️ Sentence", "group": "crime"},
    {"value": "prison", "label": "🏢 Prison", "group": "crime"},
    
    # Agriculture & Rural
    {"value": "agriculture", "label": "🌾 Agriculture", "group": "agriculture"},
    {"value": "farming", "label": "👨‍🌾 Farming", "group": "agriculture"},
    {"value": "crops", "label": "🌱 Crops", "group": "agriculture"},
    {"value": "rice", "label": "🌾 Rice", "group": "agriculture"},
    {"value": "cotton", "label": "🌿 Cotton", "group": "agriculture"},
    {"value": "sugarcane", "label": "🎋 Sugarcane", "group": "agriculture"},
    {"value": "maize", "label": "🌽 Maize", "group": "agriculture"},
    {"value": "irrigation", "label": "💧 Irrigation", "group": "agriculture"},
    {"value": "water-resources", "label": "💧 Water Resources", "group": "agriculture"},
    {"value": "dams", "label": "🏗️ Dams", "group": "agriculture"},
    {"value": "rural", "label": "🏘️ Rural", "group": "agriculture"},
    {"value": "farmers", "label": "👨‍🌾 Farmers", "group": "agriculture"},
    {"value": "msp", "label": "💰 MSP", "group": "agriculture"},
    {"value": "subsidies", "label": "💰 Subsidies", "group": "agriculture"},
    {"value": "loan-waiver", "label": "💰 Loan Waiver", "group": "agriculture"},
    {"value": "organic-farming", "label": "🌿 Organic Farming", "group": "agriculture"},
    {"value": "pesticides", "label": "🧪 Pesticides", "group": "agriculture"},
    {"value": "fertilizers", "label": "🧪 Fertilizers", "group": "agriculture"},
    {"value": "seeds", "label": "🌱 Seeds", "group": "agriculture"},
    {"value": "weather-forecast", "label": "🌤️ Weather Forecast", "group": "agriculture"},
    
    # Lifestyle & Culture
    {"value": "lifestyle", "label": "🌟 Lifestyle", "group": "lifestyle"},
    {"value": "fashion", "label": "👗 Fashion", "group": "lifestyle"},
    {"value": "beauty", "label": "💄 Beauty", "group": "lifestyle"},
    {"value": "food", "label": "🍽️ Food", "group": "lifestyle"},
    {"value": "recipes", "label": "👨‍🍳 Recipes", "group": "lifestyle"},
    {"value": "restaurants", "label": "🍽️ Restaurants", "group": "lifestyle"},
    {"value": "travel", "label": "✈️ Travel", "group": "lifestyle"},
    {"value": "tourism", "label": "🏛️ Tourism", "group": "lifestyle"},
    {"value": "hotels", "label": "🏨 Hotels", "group": "lifestyle"},
    {"value": "culture", "label": "🎭 Culture", "group": "lifestyle"},
    {"value": "traditions", "label": "🏛️ Traditions", "group": "lifestyle"},
    {"value": "festivals", "label": "🎉 Festivals", "group": "lifestyle"},
    {"value": "diwali", "label": "🪔 Diwali", "group": "lifestyle"},
    {"value": "dussehra", "label": "🏹 Dussehra", "group": "lifestyle"},
    {"value": "holi", "label": "🎨 Holi", "group": "lifestyle"},
    {"value": "ugadi", "label": "🌸 Ugadi", "group": "lifestyle"},
    {"value": "sankranti", "label": "🪁 Sankranti", "group": "lifestyle"},
    {"value": "ganesh-chaturthi", "label": "🐘 Ganesh Chaturthi", "group": "lifestyle"},
    {"value": "bonalu", "label": "🎭 Bonalu", "group": "lifestyle"},
    {"value": "bathukamma", "label": "🌺 Bathukamma", "group": "lifestyle"},
    {"value": "marriage", "label": "💒 Marriage", "group": "lifestyle"},
    {"value": "relationships", "label": "💕 Relationships", "group": "lifestyle"},
    {"value": "parenting", "label": "👶 Parenting", "group": "lifestyle"},
    {"value": "home-decor", "label": "🏠 Home Decor", "group": "lifestyle"},
    {"value": "gardening", "label": "🌱 Gardening", "group": "lifestyle"},
    
    # Opinion & Analysis
    {"value": "opinion", "label": "💭 Opinion", "group": "opinion"},
    {"value": "editorial", "label": "📰 Editorial", "group": "opinion"},
    {"value": "columns", "label": "📝 Columns", "group": "opinion"},
    {"value": "analysis", "label": "📊 Analysis", "group": "opinion"},
    {"value": "commentary", "label": "💬 Commentary", "group": "opinion"},
    {"value": "debate", "label": "🗣️ Debate", "group": "opinion"},
    {"value": "interviews", "label": "🎤 Interviews", "group": "opinion"},
    {"value": "reviews", "label": "⭐ Reviews", "group": "opinion"},
    {"value": "book-reviews", "label": "📚 Book Reviews", "group": "opinion"},
    {"value": "movie-reviews", "label": "🎬 Movie Reviews", "group": "opinion"},
    
    # Weather & Environment
    {"value": "weather", "label": "🌤️ Weather", "group": "environment"},
    {"value": "climate", "label": "🌍 Climate", "group": "environment"},
    {"value": "monsoon", "label": "🌧️ Monsoon", "group": "environment"},
    {"value": "cyclone", "label": "🌀 Cyclone", "group": "environment"},
    {"value": "floods", "label": "🌊 Floods", "group": "environment"},
    {"value": "drought", "label": "🏜️ Drought", "group": "environment"},
    {"value": "environment", "label": "🌿 Environment", "group": "environment"},
    {"value": "pollution", "label": "🏭 Pollution", "group": "environment"},
    {"value": "air-quality", "label": "💨 Air Quality", "group": "environment"},
    {"value": "water-pollution", "label": "💧 Water Pollution", "group": "environment"},
    {"value": "climate-change", "label": "🌡️ Climate Change", "group": "environment"},
    {"value": "global-warming", "label": "🌡️ Global Warming", "group": "environment"},
    {"value": "renewable-energy", "label": "⚡ Renewable Energy", "group": "environment"},
    {"value": "solar-energy", "label": "☀️ Solar Energy", "group": "environment"},
    {"value": "wind-energy", "label": "💨 Wind Energy", "group": "environment"},
    {"value": "conservation", "label": "🌿 Conservation", "group": "environment"},
    {"value": "wildlife", "label": "🦁 Wildlife", "group": "environment"},
    {"value": "forests", "label": "🌲 Forests", "group": "environment"},
    
    # Spirituality & Religion
    {"value": "astrology", "label": "⭐ Astrology", "group": "spirituality"},
    {"value": "horoscope", "label": "🔮 Horoscope", "group": "spirituality"},
    {"value": "spirituality", "label": "🕉️ Spirituality", "group": "spirituality"},
    {"value": "religion", "label": "🙏 Religion", "group": "spirituality"},
    {"value": "hinduism", "label": "🕉️ Hinduism", "group": "spirituality"},
    {"value": "temples", "label": "🛕 Temples", "group": "spirituality"},
    {"value": "tirupati", "label": "🛕 Tirupati", "group": "spirituality"},
    {"value": "shirdi", "label": "🛕 Shirdi", "group": "spirituality"},
    {"value": "devotional", "label": "🙏 Devotional", "group": "spirituality"},
    {"value": "pilgrimage", "label": "🚶 Pilgrimage", "group": "spirituality"},
    {"value": "meditation", "label": "🧘 Meditation", "group": "spirituality"},
    {"value": "philosophy", "label": "💭 Philosophy", "group": "spirituality"},
    
    # Science & Research
    {"value": "science", "label": "🔬 Science", "group": "science"},
    {"value": "research", "label": "📊 Research", "group": "science"},
    {"value": "space", "label": "🚀 Space", "group": "science"},
    {"value": "isro", "label": "🚀 ISRO", "group": "science"},
    {"value": "nasa", "label": "🚀 NASA", "group": "science"},
    {"value": "astronomy", "label": "🌌 Astronomy", "group": "science"},
    {"value": "physics", "label": "⚛️ Physics", "group": "science"},
    {"value": "chemistry", "label": "🧪 Chemistry", "group": "science"},
    {"value": "biology", "label": "🧬 Biology", "group": "science"},
    {"value": "genetics", "label": "🧬 Genetics", "group": "science"},
    {"value": "biotechnology", "label": "🧬 Biotechnology", "group": "science"},
    {"value": "innovation", "label": "💡 Innovation", "group": "science"},
    {"value": "inventions", "label": "⚙️ Inventions", "group": "science"},
    {"value": "nobel-prize", "label": "🏆 Nobel Prize", "group": "science"},
    
    # Transportation
    {"value": "automobile", "label": "🚗 Automobile", "group": "transport"},
    {"value": "cars", "label": "🚗 Cars", "group": "transport"},
    {"value": "bikes", "label": "🏍️ Bikes", "group": "transport"},
    {"value": "electric-vehicles", "label": "🔋 Electric Vehicles", "group": "transport"},
    {"value": "transport", "label": "🚌 Transport", "group": "transport"},
    {"value": "railways", "label": "🚂 Railways", "group": "transport"},
    {"value": "metro", "label": "🚇 Metro", "group": "transport"},
    {"value": "buses", "label": "🚌 Buses", "group": "transport"},
    {"value": "aviation", "label": "✈️ Aviation", "group": "transport"},
    {"value": "airports", "label": "✈️ Airports", "group": "transport"},
    {"value": "traffic", "label": "🚦 Traffic", "group": "transport"},
    {"value": "road-safety", "label": "🛣️ Road Safety", "group": "transport"},
    {"value": "fuel-prices", "label": "⛽ Fuel Prices", "group": "transport"},
    
    # Miscellaneous
    {"value": "human-interest", "label": "👥 Human Interest", "group": "misc"},
    {"value": "viral", "label": "📱 Viral", "group": "misc"},
    {"value": "weird", "label": "🤔 Weird", "group": "misc"},
    {"value": "inspirational", "label": "💪 Inspirational", "group": "misc"},
    {"value": "achievements", "label": "🏆 Achievements", "group": "misc"},
    {"value": "awards-honors", "label": "🏅 Awards & Honors", "group": "misc"},
    {"value": "obituaries", "label": "🕊️ Obituaries", "group": "misc"},
    {"value": "announcements", "label": "📢 Announcements", "group": "misc"},
    {"value": "events", "label": "📅 Events", "group": "misc"},
    {"value": "conferences", "label": "🏢 Conferences", "group": "misc"},
    {"value": "exhibitions", "label": "🖼️ Exhibitions", "group": "misc"},
    {"value": "competitions", "label": "🏆 Competitions", "group": "misc"}
]