"""added_hod_mobile

Revision ID: 25a4bccc948f
Revises: e4d8df39ae72
Create Date: 2026-01-27 12:03:47.470427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4bccc948f'
down_revision = 'e4d8df39ae72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_mobile', sa.String(length=100), nullable=True))
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('departments', 'hod_mobile')
    # ### end Alembic commands ###