"""add_hod_field_to_departments

Revision ID: e4d8df39ae72
Revises: 
Create Date: 2026-01-27 04:40:02.276462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d8df39ae72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'hod')
    # ### end Alembic commands ###